#!/bin/bash

if [ ! -f "PKGBUILD" ]; then
    echo "Error: PKGBUILD not found!"
    exit 1
fi

source PKGBUILD

jq -c -n '$ARGS.positional' --args -- "${depends[@]}"
jq -c -n '$ARGS.positional' --args -- "${makedepends[@]}"
