name: code-stats

on:
  push:
    branches:
      - main  # 只在 main 分支提交代码时触发

jobs:
  code-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate stats
        run: python3 ./code-stats/code-stats.py
          