#!/bin/bash

query_prometheus() {
    local METRIC="$1"

    curl -s -X POST \
         -H "Content-Type: application/x-www-form-urlencoded" \
         --data-urlencode "query=$METRIC{image='archlinux:latest'}" \
         http://localhost:9090/api/v1/query | \
        jq 'if (.data.result | length) != 1 then error("Length is not 1!") else (.data.result[0].value[1] | tonumber) end'
}

receive=$(query_prometheus 'container_network_receive_bytes_total')
transmit=$(query_prometheus 'container_network_transmit_bytes_total')
disk=$(query_prometheus 'container_fs_usage_bytes')

echo Receive: $receive
echo Transmit: $transmit

jq -n \
   --arg name         "$TBT_PACKAGE_NAME" \
   --arg version      "$TBT_PACKAGE_VERSION" \
   --argjson receive  $receive \
   --argjson transmit $transmit \
   '{name: $name, version: $version, receive: $receive, transmit: $transmit}'
